/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Asn1KC"
 * 	found in "/home/ccpuser/workspace/consecStb/sec_api/src/asn1_kc/asn1/Asn1KC.asn1"
 * 	`asn1c -fincludes-quoted -pdu=all -Werror`
 */

#ifndef	_Asn1KC_H_
#define	_Asn1KC_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SET_OF.h"
#include "constr_SET_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Asn1KCAttribute;

/* Asn1KC */
typedef struct Asn1KC {
	A_SET_OF(struct Asn1KCAttribute) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Asn1KC_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Asn1KC;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Asn1KCAttribute.h"

#endif	/* _Asn1KC_H_ */
#include "asn_internal.h"
